### ISSUE TITLE
Fatal error while loading config: invalid syntax (remote_homeassistant.py, line 7)

### ISSUE THREAD

**Issue by godinperson** [lukas-hetzenecker/home-assistant-remote#1]
Hi,

 I've updated my file and uncomment my old configuration and I get this error. Running on 0.80.0b3

Thanks

**Comment by lukas-hetzenecker** [comment]
That's strange, there should be nothing wrong on that line. Maybe the file download got somehow corrupted?

But, I just checked with 0.80.0b3, and there is another error when trying to connect:

```
2018-10-09 22:03:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/lukas/.homeassistant/custom_components/remote_homeassistant.py", line 159, in _recv
    if message['type'] == api.TYPE_AUTH_OK:
AttributeError: module 'homeassistant.components.websocket_api' has no attribute 'TYPE_AUTH_OK'
```

Seems like the websocket module got changed in 0.80 (possibly to support other auth mechanisms). I'll try to update my code when 0.80 gets released.

**Comment by godinperson** [comment]
Let me know once you correct it, I will test it. Really missed your integration for my raspberry in my shed.

Thanks

**Comment by lukas-hetzenecker** [comment]
Should be fixed now (thanks due @davemuench )
