### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jo-me** [lukas-hetzenecker/home-assistant-remote#12]
After noticing a dropped websocket connection in the slave instance I saw this log in the master instance:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant.py", line 206, in _recv
    callback(message)
  File "/config/custom_components/remote_homeassistant.py", line 291, in fire_event
    state = message['event']['data']['new_state']['state']
TypeError: 'NoneType' object is not subscriptable
```

I just added the Zwave stick & zwave integration to the remote HA.

**Comment by jo-me** [comment]
The custom component did not recover from this error.

**Comment by jo-me** [comment]
The error occurred again today. So initial zwave setup / device adding is probably not the issue.

**Comment by jo-me** [comment]
I found out it is related to a specific entity. After adding a try catch it caught this:
`Error parsing event data for entity persistent_notification.config_entry_discovery`

**Comment by jo-me** [comment]
Now I caught it properly. 
It occurs when you dismiss a/all notification(s) in the remote instance.
The payload looks like this. Note that `'new_state': None` .

`EventData: {'entity_id': 'persistent_notification.config_entry_discovery', 'old_state': {'entity_id': 'persistent_notification.config_entry_discovery', 'state': 'notifying', 'attributes': {'title': 'New devices discovered', 'message': 'We have discovered new devices on your network. [Check it out](/config/integrations)'}, 'last_changed': '2019-09-20T16:13:05.290038+00:00', 'last_updated': '2019-09-20T16:13:05.290038+00:00', 'context': {'id': 'a96d267c1dbf401e87541567c2576d22', 'parent_id': None, 'user_id': None}}, 'new_state': None}`

**Comment by DubhAd** [comment]
I've seen the same error (and not reconnecting) when I "busy out" the remote instance by reloading automations.
