### ISSUE TITLE
"Failed to connect to server" when "Secure" is enabled

### ISSUE THREAD

**Issue by ShadyMCShadesen** [lukas-hetzenecker/home-assistant-remote#138]
Hey,
after the new release i have a problem with connecting my instances together^^

When i am trying to connect with my instance while i have "**Secure**" enabled, it is not able to connect to the server

### Screenshot:
![firefox 2021-10-15 v3dN36](https://user-images.githubusercontent.com/31526808/137534266-7abaae02-fd70-465b-9ae6-77911b20c174.png)

**After i disabled "Secure", the instance connects without any problem.**

Instance information:
- Raspberry Pi 4 Model B
- Using duckdns
- Using nginx proxy manager
- All needed ports are open (before the breaking change from the HA-Update, it worked fine so i think there are no new ports i need to open)
- Newest HA-Version
- Newest Remote-HA-Version

**Comment by ShadyMCShadesen** [comment]
I've also tried to use the port 80 or 433 but without success^^

**Comment by ivanovd** [comment]
Same issue here. All is set according to the instructions for the new version. However, when I try to connect from one instance to the other, I see the following notification on the receiving host: 
```
Login attempt or request with invalid authentication from XXX.XX.XX.1XX (XXX.XX.XX.1XX). See the log for details.
```

In the logs:
```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:124
Integration: HTTP (documentation, issues)
First occurred: October 17, 2021, 20:19:58 (5 occurrences)
Last logged: 09:40:31

Login attempt or request with invalid authentication from XXX.XX.XX.1XX (XXX.XX.XX.1XX). (HomeAssistant/2021.10.4 aiohttp/3.7.4.post0 Python/3.9)
Login attempt or request with invalid authentication from XXX.XX.XX.1XX (XXX.XX.XX.1XX). (HomeAssistant/2021.10.5 aiohttp/3.7.4.post0 Python/3.9)
```

**Comment by 5and0** [comment]
Receiving the same issue, see below. It does authenticate on setup and I can see remote entities and services in the options for the integration. 

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:124 
Integration: HTTP (documentation, issues) 
First occurred: October 18, 2021, 6:17:38 PM (5628 occurrences) 
Last logged: 9:58:17 AM

Login attempt or request with invalid authentication from homeassistant.local (X.X.X.X). (HomeAssistant/2021.10.5 aiohttp/3.7.4.post0 Python/3.9)

**Comment by tarbax** [comment]
having the same issue here
