### ISSUE TITLE
Client exceeded max pending messages

### ISSUE THREAD

**Issue by jo-me** [lukas-hetzenecker/home-assistant-remote#14]
Hi,
I'm regularly (several times a day) seeing this message in the log of my master instance.
Is this related to home-assistant-remote?

```
Client exceeded max pending messages [2]: 512
11. September 2019, 21:19 components/websocket_api/http.py (ERROR) - message first occured at 11. September 2019, 20:33 and shows up 2 times
```

Thanks

**Comment by ACrazyConcept** [comment]
Same here! Wasn't realle sure what caused it. But I get so many of those in the log. Of course 5 remote HA's is perhaps a bit much.

**Comment by postlund** [comment]
This has been a well known problem (in Home Assistant generally) and I think the situation is better now. Please open a new issue if the problem persists.
