### ISSUE TITLE
Unhandled exception during restart fails the process of restart

### ISSUE THREAD

**Issue by elad-bar** [lukas-hetzenecker/home-assistant-remote#22]
First of all - great component, saved me lot of work syncing my 2 instances very easy, thank you!!!!

I found that during restart of HA there is an exception in the code that causes timeout of restart service which stuck the process of HA,
I applied local fix for that which is very simple, would be great if you can add it to the offical component:
1. Missing argument in the function that handles shutdown,
```self._hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, stop)``` send an argument that the ```stop``` function is not receiving which causes an issue,
I added ```event``` argument and it solved it.
```
async def stop(event):
```

2. Not handling all kind of closing websocket connection (the try / catch block of - websocket connection is closing) in ```async def _recv(self):```:
I added ```aiohttp.WSMsgType.CLOSING``` state to the if statement:
```
if data.type in (aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.CLOSED):
                            
                _LOGGER.error('websocket connection is closing')
                break
```

3. In the initialization (```async_connect```) the while loop is running always until there is an exception, the issue is when the AH is being restarted, it will try still to connect as long as the HA will disconnect all the sessions, during that time, the component's session can be terminated while it will keep retry to connect, the fix I applied for that was:
in the constructor I added:
```self._is_shutting_down = False```

in ```async_connect``` I changed ```while True:``` to ```while not self._is_shutting_down:```

in ```def close``` I added in the first line of the function:
```self._is_shutting_down = True```

**Comment by postlund** [comment]
A bit late to the ball, but I believe all of these issues are fixed now. Thanks for reporting!
