### ISSUE TITLE
Connect via Nabu Casa

### ISSUE THREAD

**Issue by Bluhme1** [lukas-hetzenecker/home-assistant-remote#27]
Trying to make a connection through Nabu Casa. Doesn't work.
Both master and instance are running Nabu Casa with different accounts
Error is 
Could not connect to ws://xxxxxxxxxxxxxxxxxx.ui.nabu.casa:8123/api/websocket, retry in 10 seconds...
When I connect using local IP there ar no problems
Anybody help, please

**Comment by lukas-hetzenecker** [comment]
Hello,

I am not familiar with Nabu Casa, but I would guess you need the following options:

```
    port: 443
    secure: true
```

as it probably runs on the standard HTTPS port

**Comment by Bluhme1** [comment]
Hi Lukas

It works. Thank you very much.

Your custom_component is much appreciated. I can now sit home and control my house at the beach.

Yours
Lars Bluhme. Denmark

**Comment by GONilsen** [comment]
did you have to open the 443 port on the router to which the home assistant is connected? I have trouble connecting via nabucasa. (have tested with duckdns, but had to move away from this as my internet provider does not offer public ip (4g broadband)
