### ISSUE TITLE
How to ensure proper status of device updates...

### ISSUE THREAD

**Issue by jfrux** [lukas-hetzenecker/home-assistant-remote#30]
It seems like it’s not properly updating state of my devices from my other instances.  And if the instances aren’t started in the right order it would seem to complicate things there as well.

Is there a service or state somewhere I can track and restart my main instance if it can’t get proper status or something? Or send a notification maybe.  Trying to track it down.

**Comment by jfrux** [comment]
UPDATE:
So if I switch something through the Hassio instance with Z-Wave controller directly, it does update my main instance device state properly.

But if I switch on a z-wave device from the physical device, it does not appear to reflect state properly.

Any tips on improving this?

**Comment by azwildfire** [comment]
> UPDATE:
> So if I switch something through the Hassio instance with Z-Wave controller directly, it does update my main instance device state properly.
> 
> But if I switch on a z-wave device from the physical device, it does not appear to reflect state properly.
> 
> Any tips on improving this?

Not all zwave devices will update their status correctly. On devices that had this behavior to me, I had to setup zwave device polling. You can read about that here: https://www.home-assistant.io/docs/z-wave/devices/#polling

**Comment by Flipsoo** [comment]
i too had that problem and came to the point, that there were a few instances of my z-wave switch one seems to update with physical buttons the other only via the web application. perhaps you have something similiar.

**Comment by postlund** [comment]
Is this really a problem with this component? Sounds more like a zwave problem to me. Anyone want to fill in? Otherwise I'd like to close this issue.

**Comment by postlund** [comment]
I'm closing this now, please open again or create a new issue if problem persists.
