### ISSUE TITLE
Calling services from python script on remote entity ot working

### ISSUE THREAD

**Issue by jacekpaszkowski** [lukas-hetzenecker/home-assistant-remote#31]
Hi,

I run version 2.1 of your component - it's great.
But i've noticed a problem with calling sevrices via python script. It doesn't work, no errors in logs.
Same service call works ok from UI or directly from yaml.

Here is python snippet:
service_data_hvac = { 'entity_id': thermostat_entity }
[.....]
service_data_hvac['hvac_mode'] = 'heat'
hass.services.call('climate', 'set_hvac_mode', service_data_hvac)

In log i see that script was executed and there are no any errors.

2020-01-06 11:48:35 INFO (SyncWorker_18) [homeassistant.components.python_script] Executing set_proper_floor_heating_mode.py: {'thermostat_entity': ['climate.slave1_thermofloor_as_heatit_thermostat_tf_021_mode_2']}

Please help.

**Comment by jacekpaszkowski** [comment]
ok, i think the issue is the sequence of two calls one after another:
hass.services.call('climate', 'set_hvac_mode', service_data_hvac)
hass.services.call('climate', 'set_preset_mode', service_data_preset)

I've noticed than my thermostat blinks for a second and then turns off.

**Comment by jacekpaszkowski** [comment]
It was necessary to add some delay between those two calls.

**Comment by lukas-hetzenecker** [comment]
Thanks for the report, i'm happy you got it working :)
