### ISSUE TITLE
Feature request: remote HA connection state sensor

### ISSUE THREAD

**Issue by jacekpaszkowski** [lukas-hetzenecker/home-assistant-remote#35]
Hi, i would be nice to have a sensor indicating the state of connection with remote HA.

BTW Thank you for very useful component :)

**Comment by lukas-hetzenecker** [comment]
Good idea, would accept such a pull request ;)

**Comment by jacekpaszkowski** [comment]
@lukas-hetzenecker please take a look https://github.com/lukas-hetzenecker/home-assistant-remote/pull/36

**Comment by jacekpaszkowski** [comment]
@lukas-hetzenecker  PR updated :)

**Comment by jacekpaszkowski** [comment]
so it's time close this issue :)
