### ISSUE TITLE
access_token how to set it up

### ISSUE THREAD

**Issue by cathmonster** [lukas-hetzenecker/home-assistant-remote#37]
Hi,
so for two instances of HA, I setup as custom_components remote_homeassistant.

config is super simple but access_token is required and when I created on master latest version HA and on remote I get on slave - remote request with invalid auth
Could someone explain why is this...

**Comment by N-l1** [comment]
To generate an access token, click on the user icon (on slave) and all the way on the bottom is a section called **Long live access tokens**. Click create token and you'll be able to generate an access token.
