### ISSUE TITLE
Setup instructions are not clear

### ISSUE THREAD

**Issue by dionrowney** [lukas-hetzenecker/home-assistant-remote#38]
It is not clear what needs to be done on the main host connecting out and or the remote host authentication-wise or if anything is needed at all.

Can you please update the readme to include an installation step by step and on what host steps are performed?

Does the remote_homeassistant module get installed on both the main and remote HA hosts?

**Comment by dionrowney** [comment]
I think all you need to add is pre-requisites indicating that the remote profile API token needs to be setup and on the host config that the token must be indicated.  this would have cleared up my confusion.  

you could indicate that the remote unit has to be set by "obtaining a token ("Long-Lived Access Token") by logging into the frontend using a web browser, and going to your profile http://IP_ADDRESS:8123/profile. " to enable api acceess.

**Comment by JoostHman** [comment]
Hi all, I also have a question about the setup. 

I have a master and slave instance connected and slave devices show up correctly on the master. I can see the correct state of my switches on my slave on the master, so if I switch to "on" on the slave this state mimics correctly on the master.

So all good except that I cannot operate the slave switches from my master. What am I missing? 

remote_homeassistant:
  instances:
  - host: xxx.xxx.xxx.xxx
    port: 8123
    access_token: iojeijfmgJKhVtrew1jhjrtsQiLCJhb-etc
    secure: false
    verify_ssl: false
    entity_prefix: "GardenPi_"
    include:
      domains:
      - switch

**Comment by dionrowney** [comment]
You are missing nothing setup sounds right.  **Open as new ticket** and not in this one or use home assistant discord as this is a bug issue request to fix documentation.

**Comment by lukas-hetzenecker** [comment]
Specified websocket API is enabled out of box, nothing needs to be installed on the secondary instances.
