### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by jasperbom** [lukas-hetzenecker/home-assistant-remote#4]
I'm getting this issue....
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/homeassistant/.homeassistant/custom_components/remote_homeassistant.py", line 158, in _recv
    if message['type'] == api.TYPE_AUTH_OK:
AttributeError: module 'homeassistant.components.websocket_api' has no attribute 'TYPE_AUTH_OK'
```

**Comment by MrUkleja** [comment]
Same here ... did you manage to solve this?
I tried with and without api_password - same error

**Comment by davemuench** [comment]
They broke up the websocket API a few versions ago in home assistant. You need to edit this line near the top of remote_homeassistant.py from:

import homeassistant.components.websocket_api as api

to:

import homeassistant.components.websocket_api.auth as api

Quick hack but it seems to work. I'm just starting to play around with this component, it's a shame it wasn't accepted. I'd send a PR for this one liner but I don't know if the author has abandoned it or not.

**Comment by lukas-hetzenecker** [comment]
@davemuench please send a PR :-)

I'm still using this component myself, but unfortunately only with Home-Assistant 0.79.3 (I can't upgrade yet, because I want to port several andrey-git/home-assistant-custom-ui UI elements to Lovelace first; and this takes time..)

**Comment by davemuench** [comment]
@lukas-hetzenecker Will do - and glad to hear you are still using it. I've only had it working for 24 hours now after searching for weeks on a way to link two HA instances, and it's the only method that works even slightly.

**Comment by lukas-hetzenecker** [comment]
Merged :)
