### ISSUE TITLE
Slave visible but not able to operate from master

### ISSUE THREAD

**Issue by JoostHman** [lukas-hetzenecker/home-assistant-remote#43]
So will open this as a new topic.

I have a master and slave instance connected and slave devices show up correctly on the master. I can see the correct state of my switches on my slave on the master, so if I switch to "on" on the slave this state mimics correctly on the master.

So all good except that I cannot operate the slave switches from my master. What would be the best way to investigate what is not working? When I try to switch from master the following appears in the log of the master:

Unable to find referenced entities switch.gardenpi_pool_lights
11:03:31 PM – helpers/service.py (WARNING) - message first occurred at 10:54:31 PM and shows up 3 times

Thanks a lot for your help!

**Comment by ThePirat91** [comment]
Hello, I have exactly the same problems.
Hassio 0.109.6 (both master and slave) and home-assistant-remote last version (2.1) on master.
What could be the reason for that?

Thanks

**Comment by tiagofreire-pt** [comment]
Same issue, here. With both HA connected by WAN, with HA 0.110.4 (master and slave).

**Comment by tiagofreire-pt** [comment]
This seems to come from using the version "2.1", as the one proposed by the HACS custom component. I re-installed this remote_homeassistant component but with the "master" version. So far, no issues.

**Comment by ThePirat91** [comment]
> 
> 
> This seems to come from using the version "2.1", as the one proposed by the HACS custom component. I re-installed this remote_homeassistant component but with the "master" version. So far, no issues.

Just tried and......it didn't work.
I always have this error on master log

`2020-06-04 17:47:58 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.my_light`

**Comment by christcb03** [comment]
This is happening for me too, did anyone find an answer?

**Comment by patdemko** [comment]
I just started playing around with this integration and I'm seeing this issue as well.  I tried changing from 2.1 to the master to 2.0 and they all gave the same result.

=======================================
Log Details (WARNING)
Logger: homeassistant.helpers.service
Source: helpers/service.py:422
First occurred: 4:17:40 PM (4 occurrences)
Last logged: 4:29:16 PM

Unable to find referenced entities light.ha2_centralite_4257050_rzhac_837a4e04_on_off
=======================================

**Comment by patdemko** [comment]
So it turns out this issue is very similar to the [one down below](https://github.com/lukas-hetzenecker/home-assistant-remote/issues/32). 

Someone there said removing the entity_prefix from their configuration fixed it for them.  I tried that and it fixed the issue for me as well.

**Comment by ThePirat91** [comment]
> 
> 
> So it turns out this issue is very similar to the [one down below](https://github.com/lukas-hetzenecker/home-assistant-remote/issues/32).
> 
> Someone there said removing the entity_prefix from their configuration fixed it for them. I tried that and it fixed the issue for me as well.

It fixed my issue too.

**Comment by acigl** [comment]
Same issue. Did some testing. More details.

Master: Ver 0.113.1
Remote: Ver 0.116.4
both virtual env on RPi.

Using  **entity_prefix: "Prit_B_"**:

Master Configuration:
```
remote_homeassistant:
  instances:
  - host: __HOST__
    port: __PORT__
    secure: true
    verify_ssl: false
    access_token: __TOKEN__
    entity_prefix: "Prit_B_"
    include:
      domains:
      - sensor
      - switch
    subscribe_events:
    - state_changed
    - service_registered
```
Remote configuration:
```
switch Outputs:
  - platform: rpi_gpio
    ports:
      4:  Out_01
```

Connection OK.
Entityes are presented in frontend without "friendly_name" Prefix! Internal it is OK:
switch.prit_b_out_01 | off | friendly_name: Out_01
-- | -- | --

Sensors are working OK. Master is getting correct values from Remote sensors (friendly name without prefix).

When you try to toggle Remote switch I am getting following error in the log:

`2020-10-26 23:29:53 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.prit_b_out_01`

It seems that Master is trying to toggle Entity with Prefix on Remote which is not existing?

Without **Prefix** usage:
I am facing stability issue of the switch. When toggling Remote switch is constantly continuing to switch ON and OFF :-( .
Is this any help?

**Comment by tiagofreire-pt** [comment]
@lukas-hetzenecker , seems the issue remains. Every time the slave gets its router rebooted, the master remains with "connected" state and does not restart the connection.

HA 0.116.4, with remote home assistant 2.3.
