### ISSUE TITLE
remote home assistant slave devices not connected automatically after WAN outage

### ISSUE THREAD

**Issue by callebridholm** [lukas-hetzenecker/home-assistant-remote#44]
Hi,
I have this setup at two locations, one haster home assistant at a stable fiber WAN link and a "slave" home assistant at with a 4G mobile WAN link. Sometimes the 4G WAN links drops for some time and I think that is normal with mobile WAN links. Sometimes everything works when 4G WAN link is back but sometimes not. 
Another case is that if I restart the slave home assistant device after for example changed some configuration the "remote entites" in the haster home assistant are not updated and the connection between them are lost. 

The solution to get this connection up and running aging is to restart the master home assistant device and then everything is ok.

I am wondering if it is possible to implement some kind of heartbeat in this plugin so the master home assistant talk to the "slaves" regularly even if no event is sent between them. Then if that fail maybe try to reestablish the connection between them.

**Comment by lukas-hetzenecker** [comment]
what you are describing is actually what _should_ already be happening - when the websocket connection is anyhow interrupted, the remote entities should disappear automatically. Then every 10 seconds, a connection should be attempted again. If successful, entities should appear again.

This is working in my setup, no restarts whatsoever needed, but how you are describing it there seems to be a bug somewhere in that logic.

**Comment by callebridholm** [comment]
> what you are describing is actually what _should_ already be happening - when the websocket connection is anyhow interrupted, the remote entities should disappear automatically. Then every 10 seconds, a connection should be attempted again. If successful, entities should appear again.
> 
> This is working in my setup, no restarts whatsoever needed, but how you are describing it there seems to be a bug somewhere in that logic.

Ok is it possible for me to find some logs at my setups that can help you find this?

**Comment by callebridholm** [comment]
Now it happened again, 2 days without updates from the remote HA in the garage
![image](https://user-images.githubusercontent.com/7568428/81605667-1ac8bd80-93d2-11ea-98f0-014743fecfed.png)

**Comment by Ex3mXX** [comment]
Same for me, my slave is on a 3G modem and when it change WAN IP it take some time for the duckdns.org to change the redirect and under that time the connection is lost and don't get back up until i reboot the master. As said before, would be good to be able to get som kind of logs.

**Comment by florianec** [comment]
Is it possible that this issue only appear when using a Dynamic DNS?
Maybe home-assistant-remote can't recognize cause something is cached (like some .js in a browser). I have the same issue. 

I access my remote instance over https://mysuper.subdomain.de:8125.
When i change the Port in my Router to block it, for example to 8126,
the master instance has no clue that it is gone. Entitys don't disappear and 
no error logs. After a while (10-15min) this appears in the log
_(not sure if related, could be some other problem, maybe someone here check if he had the same logs)_ :

`2020-06-15 15:47:28 ERROR (MainThread) [homeassistant.components.rest.switch] Error while fetching data: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 198, in async_update
    await self.get_device_state(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 210, in get_device_state
    self._resource, auth=self._auth, headers=self._headers
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
2020-06-15 15:53:08 ERROR (MainThread) [homeassistant.components.rest.switch] Error while fetching data: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 198, in async_update
    await self.get_device_state(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 210, in get_device_state
    self._resource, auth=self._auth, headers=self._headers
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
2020-06-15 15:53:38 ERROR (MainThread) [homeassistant.components.rest.switch] Error while fetching data: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 198, in async_update
    await self.get_device_state(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 210, in get_device_state
    self._resource, auth=self._auth, headers=self._headers
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
2020-06-15 15:56:13 ERROR (MainThread) [homeassistant.components.rest.switch] Error while fetching data: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 198, in async_update
    await self.get_device_state(self.hass)
  File "/usr/src/homeassistant/homeassistant/components/rest/switch.py", line 210, in get_device_state
    self._resource, auth=self._auth, headers=self._headers
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer`

After i change the port back and verify connection is ok, the master instance still don't recognize it and doesn't update. Only a restart could solve this.

**Comment by lokanx** [comment]
I also have the same problem over a 3g/4g router. I connecting using nabu casa.

I see this on the host trying to connect to.

Logger: homeassistant.components.websocket_api.http.connection.1810656624
Source: components/websocket_api/http.py:47 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 24 juni 2020 2:53:50 (1 occurrences) 
Last logged: 24 juni 2020 2:53:50

Disconnected: Did not receive auth message within 10 seconds.

**Comment by plonkis** [comment]
I have the same problem but master and slaves are on the same local LAN… If I reboot the master it will work again for 1-2 days.

**Comment by fti7** [comment]
Same Problem here :-(

**Comment by plonkis** [comment]
Thanx for the update, it is looking very prommising!

**Comment by callebridholm** [comment]
Hade been running version 2.2 with extra features for handling connection problems but tonight when my home assistant with 4G in my garage list internet for 3-4 minutes the connection at my master HA was not resumed. How do I collect all logs you need to troubleshoot this? A reboot of master HA solved the problem 
![0DB8371D-93F8-4A9E-87A9-4C0088AD8966](https://user-images.githubusercontent.com/7568428/93848449-dddad480-fca9-11ea-9030-f2aebd00ae63.png)
![2B3C21A1-6624-47F4-A0E8-0A2F210022D7](https://user-images.githubusercontent.com/7568428/93848453-e03d2e80-fca9-11ea-8b9b-05c9e142c95c.png)

**Comment by plonkis** [comment]
8 days of testing and 0 problem for me, it usually lost connection within 48 hrs or less.
It handles re connections great. my network is LAN and Wifi based no 3g/4g etc.

**Comment by mindtripper** [comment]
> 8 days of testing and 0 problem for me, it usually lost connection within 48 hrs or less.
> It handles re connections great. my network is LAN and Wifi based no 3g/4g etc.

This is my experience as well in a LAN configuration. Having 3 different HA instances in a hub-spoke configuration.

**Comment by jaym25** [comment]
This is how I fixed it...  starting with line 153 thru "async def _init(self):"
It stays connected for short interruptions and reconnects without fail including on network disconnects...
It has been extremely stable and reliable and eliminates logs every 10 seconds while disconnected.
This component can also be used bi-directionally with multiple systems being both masters and slaves...
This should be done as a pull request if I had the time to learn how to do that...

        self._connection = None
        self._entities = set()
        self._handlers = {}
        self._remove_listener = None
        self._remove_entities = True

        self._instance_attrs = {
            'entity_prefix': self._entity_prefix,
            'host': self._host,
            'port': self._port,
            'secure': self._secure,
            'verify_ssl': self._verify_ssl
        }

        self._entities.add(self._connection_state_entity)
        self._hass.states.async_set(self._connection_state_entity, STATE_CONNECTING, self._instance_attrs)

        self.__id = 1

    def _prefixed_entity_id(self, entity_id):
        if self._entity_prefix:
            domain, object_id = split_entity_id(entity_id)
            object_id = self._entity_prefix + object_id
            entity_id = domain + '.' + object_id
            return entity_id
        return entity_id

    @callback
    def _full_url(self):
        """Full url for connection."""
        return '%s://%s:%s/api/websocket' % (
            'wss' if self._secure else 'ws', self._host, self._port)

    @callback
    def _short_url(self):
        """Short url for display."""
        return '%s://%s:%s' % (
            'wss' if self._secure else 'ws', self._host, self._port)

    async def async_connect(self):
        """Connect to remote HA websocket..."""
        url = self._full_url()
        urld = self._short_url()

        session = async_get_clientsession(self._hass, self._verify_ssl)
        conn_err = False
        self._hass.states.async_set(self._connection_state_entity, STATE_CONNECTING, self._instance_attrs)

        while True:
            try:
                _LOGGER.info('Connecting to %s', urld)
                self._connection = await session.ws_connect(url)
            except aiohttp.client_exceptions.ClientError as err:
                if not conn_err:
                    _LOGGER.error(
                        'Could not connect to %s, retry every 10 seconds...', urld)
                conn_err = True
                self._hass.states.async_set(self._connection_state_entity, STATE_RECONNECTING, self._instance_attrs)
                await asyncio.sleep(10)
            else:
                _LOGGER.info(
                    'Connected to HA websocket at %s', urld)
                self._hass.states.async_set(self._connection_state_entity, STATE_CONNECTED, self._instance_attrs)
                break

        async def stop():
            """Close connection."""
            if self._connection is not None:
                _LOGGER.error('Websocket connection at %s closing...', urld)
                await self._connection.close()
            self._hass.states.async_set(self._connection_state_entity, STATE_DISCONNECTED)

        self._hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, stop)

        asyncio.ensure_future(self._recv())

    def _next_id(self):
        _id = self.__id
        self.__id += 1
        return _id

    async def _call(self, callback, message_type, **extra_args):
        _id = self._next_id()
        self._handlers[_id] = callback
        try:
            await self._connection.send_json(
                {'id': _id, 'type': message_type, **extra_args})
        except aiohttp.client_exceptions.ClientError as err:
            _LOGGER.error('Remote websocket connection closed: %s', err)
            await self._disconnected()

    async def _disconnected(self):
        if self._remove_entities:
            # Remove all published entries
            for entity in self._entities:
                self._hass.states.async_remove(entity)
        if self._remove_listener is not None:
            self._remove_listener()
        self._remove_listener = None
        if self._remove_entities:
            self._hass.states.async_set(self._connection_state_entity, STATE_DISCONNECTED)
            self._entities = set()
        self._remove_entities = True
        asyncio.ensure_future(self.async_connect())

    async def _recv(self):
        """Retreive data from remote instance."""

        while not self._connection.closed:
            try:
                data = await asyncio.wait_for(self._connection.receive(), 30)
            except aiohttp.client_exceptions.ClientError as err:
                _LOGGER.error('Remote websocket connection closed: %s', err)
                break
            except:
                _LOGGER.error('Websocket connection lost...')
                await self._connection.close()
                break

            if not data:
                break

            if data.type in (aiohttp.WSMsgType.CLOSE, aiohttp.WSMsgType.CLOSED):
                _LOGGER.error('Websocket connection is closing...')
                break

            if data.type == aiohttp.WSMsgType.ERROR:
                _LOGGER.error('Websocket connection had an error...')
                break

            try:
                message = data.json()
            except TypeError as err:
                _LOGGER.error('Could not decode data (%s) as json: %s', data, err)
                break

            if message is None:
                break

            _LOGGER.debug('Received: %s', message)

            if message['type'] == api.TYPE_AUTH_OK:
                await self._init()

            elif message['type'] == api.TYPE_AUTH_REQUIRED:
                if not (self._access_token or self._password):
                    _LOGGER.error('Access token or api password required, but not provided')
                    return
                if self._access_token:
                   data = {'type': api.TYPE_AUTH, 'access_token': self._access_token}
                else:
                   data = {'type': api.TYPE_AUTH, 'api_password': self._password}
                try:
                   await self._connection.send_json(data)
                except Exception as err:
                   _LOGGER.error('Could not send data to remote connection: %s', err)
                   break

            elif message['type'] == api.TYPE_AUTH_INVALID:
                _LOGGER.error('Auth invalid, check your access token or API password')
                await self._connection.close()
                return

            else:
                callback = self._handlers.get(message['id'])
                if callback is not None:
                    try:
                       callback(message)
                    except:
                       await self._connection.close()
                       self._remove_entities = False
                       break

        await self._disconnected()

    async def _init(self):

**Comment by postlund** [comment]
I believe I have fixed most re-connect issues in the latest release. If possible, please give it a try if you are experiencing problems and let me know if something isn't working.

**Comment by callebridholm** [comment]
> I believe I have fixed most re-connect issues in the latest release. If possible, please give it a try if you are experiencing problems and let me know if something isn't working.

Yes at least with version 3.0 and 3.1 it get a lot better, great job! Will close this now
