### ISSUE TITLE
Remove requirement of port in hostname 

### ISSUE THREAD

**Issue by stevenjev** [lukas-hetzenecker/home-assistant-remote#47]
I connect to my HA server with a URL such as:

`https://myha.server.com`

with no port allowed in the URL. I do not know enough to modify and make a pull request. But I was able to solve the issue for myself by modifying lines 185 & 186 to remove the port:

```
return '%s://%s/api/websocket' % (
            'wss' if self._secure else 'ws', self._host)
```

With this change, the connection works. I wonder (since I imagine I cannot be the only one with this connection type) if the default behavior could be that with no port specified in the config, then there is no port added to the host URL rather than defaulting to 8123.

Thanks!

**Comment by daxda** [comment]
Hi, I have your same problem, where to reach an installation on my server behind a reverse proxy (Apache). I tried to modify it as @stevenjev said, but it still seems to connect to port 8123. Is it possible to remove the default port on 8123?

**Comment by lukas-hetzenecker** [comment]
Sorry, but will leave the default setting of 8123 as this is the default port of home-assistant, when it's not behind a load balancer.
Port for plain "https://" is 443, so please use instead for https (or 80 for http)
