### ISSUE TITLE
alarm_control_panel manual

### ISSUE THREAD

**Issue by ttocsr** [lukas-hetzenecker/home-assistant-remote#49]
https://www.home-assistant.io/integrations/manual/
This integration partially works.  I can see if the panel is armed or disarmed.
But I can not arm or disarm the alarm panel.

I get the following error.
Failed to call service alarm_control_panel/alarm_disarm. Service not found.

**Comment by akaroczi** [comment]
I got the same error with the vacum object. When I try to control my vacum from remote instance, i got the following error:

 Failed to call service vacum/pause. Service not found.

**Comment by akaroczi** [comment]
@ttocsr 

I got the same error with the vacuum object and i solved it.

There is a special note in the [README.md](https://github.com/lukas-hetzenecker/home-assistant-remote#special-notes)

I had to set an emtpy vacuum object inside the configuration yaml. You should try it. Just type it alarm_control_panel: into your conf file

**Comment by ttocsr** [comment]
I missed that, probably because it mentioned switch (which I don't have in my remote instance)
That resolved my issue.
Thank you @akaroczi
