### ISSUE TITLE
HACS release is outdated

### ISSUE THREAD

**Issue by sibbl** [lukas-hetzenecker/home-assistant-remote#50]
When installing the component via HACS, the version 2.1 is installed. This corresponds to the git tag from ~Nov 2019.

I encountered issues setting the component up until I found out that the installed version didn't match the master branch and lot of the issues were already fixed.

**Comment by aksvenk** [comment]
+1 @lukas-hetzenecker could you please tag a new version?

**Comment by lukas-hetzenecker** [comment]
Released 2.2 - sorry it took so long
