### ISSUE TITLE
turn of zone from remote hass

### ISSUE THREAD

**Issue by ranrinc** [lukas-hetzenecker/home-assistant-remote#51]
How can I turn off or exclude zone from remote hass? thanks

**Comment by huemcos** [comment]
I also need to know how to do this.

**Comment by huemcos** [comment]
I figured it out... zone is an entity so it can be excluded... try this:
`    exclude:
      entities:
      - zone.home`

**Comment by postlund** [comment]
Solution provided by @huemcos, will close issue.

**Comment by Mearman** [comment]
Hi there. After trying this, the home entity on my main HAss instance disappears
