### ISSUE TITLE
Temp and Humidity Sensors update issue

### ISSUE THREAD

**Issue by huemcos** [lukas-hetzenecker/home-assistant-remote#52]
Hi, thanks for the nice component, very useful for me.
I have temperature and humidity sensors that update every 60 seconds on another HA instance. Locally, they work fine.
But values are not updated consistently on my main HA machine. Sometimes it takes 15-30 minutes before they get updated.

**Comment by lbouriez** [comment]
I am seeing a similar issue.
I have a slave instance that I use to get some temperature sensor, humidity sensor..
My main instance with home-assistant-remote seems to loose the contact at some point.
After a reboot, everything works but with time, the sensor are not uptdated regularly.
![image](https://user-images.githubusercontent.com/4749766/95384015-040f8f80-08ba-11eb-9815-20c28db0556d.png)

**Comment by kalyway101** [comment]
I also have the same issue. My main instance of home assistant doesn't update the Temperature and Humidity sensors on my remote instance unless the remote instance is rebooted.

**Comment by Highvolt** [comment]
I was having the same issue after configuring using the UI. I solved my problem by subscribing the following events in the last step of the configuration:

- state_changed
- service_registered

**Comment by postlund** [comment]
I have pushed #93 which makes sure these events are always subscribed to, no matter if they are listed or not. So that should solve the issue once merged, I hope.

**Comment by postlund** [comment]
#93 is merged, will be part of next release.
