### ISSUE TITLE
Could not connect to wss://........... , retry in 10 seconds 

### ISSUE THREAD

**Issue by lancelon** [lukas-hetzenecker/home-assistant-remote#53]
Get this error and a restart of the opposite end usually fixes things - but what causes it? Once it appears it doesn't resolve on its own.

Thanks! :

**Comment by lukas-hetzenecker** [comment]
This looks like the remote instance indeed cannot be reached.
Have you tried to directly connect to the remote via the browser (using the same details connection details as in the configuration.yaml)? If yes, does this work correctly?

**Comment by Jens-Wymeersch** [comment]
@lukas-hetzenecker I have just the same issue and I am able to connect to the remote instance. I'm using the api password by the way. Maybe with the token, it might resolve itself but don't have a clue how to get the token from the remote instance.

**Comment by Jens-Wymeersch** [comment]
@lukas-hetzenecker After I changed to the token option. All worked as designed !
