### ISSUE TITLE
step by step please

### ISSUE THREAD

**Issue by Vartkat** [lukas-hetzenecker/home-assistant-remote#56]
I don't know if this could be considered an issue but I don't understand how to make this work. 
I read, once, twice, ten times the instructions... Still

1) I added the integration using HACS but if I go to Configuration->Integration and press + there's no integration with the 'remote' word in its name

2) As far as I understand, the slave Home Assistant machine is already a server which answers requests from the main one, the master.
If so, do I still have to add
`websocket_api:` 
in the slave machine configuration.yaml ? as stated in https://www.home-assistant.io/integrations/websocket_api/

3) I found (2) while I was looking for the port number of the websocket, where do I find it ? If it's 8123, why would I change this port on a standard Home Assistant install. If it's the standard Home Assistant port number, not once it is mentioned "if ever you changed HA's port number you can specify your specific port number" the readme only says port number as if everybody knows what is the websocket api port number.

4) Nohting in the readme says that the configuration should be added to the master configuration.yaml file (and even writing this I'm still not sure of it)

So please, be kind enough to write a few lines with very clear instructions on 
- what should be done on the **master**, 
- what should be done on the **slave**, 
- where the find the parameters (IP, port,etc), 
- when to restart Home Assistant and 
- how to acknoledge everything has been done right.

Thanks for your help

Regards

Vart

**Comment by lukas-hetzenecker** [comment]
1. Correct, no graphical configuration is available for home-assistant-remote

2. Master = instance where entities of slave/secondary instance are added.
Slave/secondary needs **no** configuration at all (websocket_api is always enabled by default). 
Master needs `remote_homeassistant` instances configuration, that specifies how to connect to slaves.

3. IP/Port needs to be exactly the same, as you'd access the slave/secondary instance via browser.
E.g. if you're using http://10.0.0.5:8123 to open home-assistant on the slave, configuration on the master needs to be:

```
remote_homeassistant:
  instances:
  - host: 10.0.0.5
    port: 8123
    secure: false
```

You'd (probably) have another port, if you can access Home-Assistant from the internet via a proxy - e.g. via https://homeassistant.yourdomain.tld (in this case, host is homeassistant.yourdomain.tld, port 443 and secure: true).

After adding this configuration to the master, the master needs to be restarted.
