### ISSUE TITLE
Component sensor says it's connected when connection is refused for lack of token or password

### ISSUE THREAD

**Issue by Mastiffen** [lukas-hetzenecker/home-assistant-remote#65]
I was going to use this without any security at all, since I don't need it (you'd have to get past my pfSense and know the internal IP address to get to my Hass instances - they are not accessible from outside). It seemed to work, but nothing populated. Finally after a tip from @Postlund I checked the master Hass log, and that said it couldn't connect without an API password or a token. Adding a token fixed it right away. But the sensor said “hytte pi remote connection 192 168 1 101 8123” and had this info:

192.168.1.101
port
8123
secure
false
verify ssl
true
entity prefix
hytte_pi_

Here's the tread about this: 
https://community.home-assistant.io/t/master-ha-instance-with-multiple-slaves/109849/79?u=mastiff

**Comment by lukas-hetzenecker** [comment]
I can reproduce this issue, working on a fix

**Comment by Mastiffen** [comment]
Great, thanks! Not a problem for me now, since I got help to see it, but I'm glad you're so quick on the draw. :)

**Comment by lukas-hetzenecker** [comment]
@postlund 
> The component should however not allow this configuration in the first place. One of access key or password should be required. I would appreciate if you opened an issue about it over at GitHub so I can fix it. Just refer to this post and tag me. Thanks! :+1:

Not necessarily - there is e.g. the `trusted_networks` "authentication provider" ( https://www.home-assistant.io/docs/authentication/providers/ ) which can bypass the need of an authentication for a network range. 
So in general, access key / api password is optional.
