### ISSUE TITLE
Any way to filter out specific entities from a remote machine?

### ISSUE THREAD

**Issue by krasatos** [lukas-hetzenecker/home-assistant-remote#7]
Hey, 
I'm using this component without a prefix.
Is there some way to filter out a specific entity to not be passed to my master HA?
Specifically group.all_switches which causes [problems ](https://community.home-assistant.io/t/multiple-all-switches-groups-in-states-page-while-using-home-assisstant-remote/122757)in my master HA.
Thanks in advance.

**Comment by theit8514** [comment]
I had a similar problem with the Home zone getting overwritten on the master HA. Adding the prefix solved the issue but perhaps supporting the common include_entities/include_domains and exclude_entities/exclude_domains logic would be useful.

**Comment by lukas-hetzenecker** [comment]
Yeah, that would be a really useful feature.
`include_entities` should be enough, if it also supports wildcards. 
Would definitely merge a pull request for that one 😄

**Comment by Cybersmurfen** [comment]
+ 1 on include_entities - or include_domains
I'm using this plugin to monitor some remote sensors, and I get alot of extra automations, calendars, lights, switches etc that I really don't want to see in the lists - even if I use the prefix.

**Comment by lukas-hetzenecker** [comment]
As Hacktoberfest is currently ongoing I figured now would be the best time to implement this.
Seems like pull requests for own repositories are a gray area, but generally allowed. But because so many people want this feature, it should hopefully be okay :-) 

Implemented in #18, expect a new release soon
