### ISSUE TITLE
Will home-assistant-remote sync all data or just the included entities?

### ISSUE THREAD

**Issue by callebridholm** [lukas-hetzenecker/home-assistant-remote#74]
Hi,

I have used home-assistant-remote for long time now and it works great. I have one primary HA at my house with fiber and one remote at my garage that use 4G. Everything works today and I only get entities I includes to my main HA GUI. 
Now I plan to install a network camera and connect to my HA in my garage. The camera should only be used to send snapshots from the garage slave HA directly when the garage door is open, I am not interested to view some video feeds or get that to the main HA. 
My question is if home-assistant-remote get all data from the slave HA and then filter our all entities that I not has included in my main HA configuration or do home-assistant-remote only transfer data from slave HA to main HA from the entities I included? My 4G in the garage has limited data each months so I don´t want the camera stream to be transferred to my main HA, that's why I ask this :)

**Comment by postlund** [comment]
There's no way in the websocket API to apply filtering on individual entities like that, all of that filtering is performed by the instance running this component I'm afraid.

**Comment by lukas-hetzenecker** [comment]
Also: Cameras generally won't work with this component, no matter how they are integrated (see #29). Sorry about that.
