### ISSUE TITLE
KeyError: 'uuid'  after upgrade to 3.0

### ISSUE THREAD

**Issue by jo-me** [lukas-hetzenecker/home-assistant-remote#79]
Hi,

I had the previous versions running fine with yaml config and just upgraded to v3.0 and there seems to be an issue with the uuid.
The master instance is running HA core 0.118.5, the remote HA instance is on 0.103.6

`Logger: custom_components.remote_homeassistant.config_flow
Source: custom_components/remote_homeassistant/config_flow.py:72
Integration: Remote Home-Assistant (documentation)
First occurred: 19:50:42 (1 occurrences)
Last logged: 19:50:42

import of 192.168.178.45 failed
Traceback (most recent call last):
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 158, in async_step_import
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/remote_homeassistant/config_flow.py", line 72, in validate_input
    return {"title": info["location_name"], "uuid": info["uuid"]}
KeyError: 'uuid'`

**Comment by postlund** [comment]
For all the new logic to work, we need a unique identifier of the remote instance to map to our local config (entry). The discovery api provides a UUID that we use, but I wasn't really aware that it was added quite late. What is needed is this PR:

https://github.com/home-assistant/core/pull/35624

Which was included in 0.111. So the minimum required version of the remote host is 0.111 (regardless of setting up via config flow or YAML, just to be clear). So you will have to upgrade your remote instance to continue to use this component and we should make it more clear that this dependency exists. Sorry about the inconvenience!

**Comment by jo-me** [comment]
Hmm yeah, I suspected something like this when I searched your code. 
Hadn't updated the other one because its just a mule for zwave and I'm very wary of breaking that (again) as Zwave is just a mess of an implementation. 

The minimum remote version is definitely something that should be documented and mentioned in the release notes if it changes. 

Anyway, thanks for improving this component! 👍

**Comment by lukas-hetzenecker** [comment]
I've added "Requires home-assistant >= 0.111 for remote instances (#79)" to the breaking changes in the release notes, which should be shown to everybody updating via HASS

**Comment by postlund** [comment]
@lukas-hetzenecker That is good enough for now. But we should check if `uuid` is present and provide a decent error message if it isn't. We need to do the same when connecting as well, to handle YAML config too.

**Comment by DubhAd** [comment]
> Hadn't updated the other one because its just a mule for zwave and I'm very wary of breaking that (again) as Zwave is just a mess of an implementation.

FYI, I'm in the same boat (my Z-Wave instance is on 0.88.2). What I did for this is spin up a _very_ minimal Docker instance of HA to run the 2.3 release of HA Remote. That connects to my Z-Wave instance _and doesn't add a prefix_. My main instance now connects to that, as it did before. Everything works, and I don't have to worry about updating my main instance.

Yes, it's a horrible kludge, but it's also testament to HA Remote that it works seamlessly despite this 😀
