### ISSUE TITLE
Setup failed for remote_homeassistant: No setup function defined.

### ISSUE THREAD

**Issue by michalterbert** [lukas-hetzenecker/home-assistant-remote#8]
Hi!
I would like to use that custom component, but doesnt work on Hassio v0.94.3.
Below errors:
```
2019-07-08 11:52:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for remote_homeassistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-07-08 11:52:30 ERROR (MainThread) [homeassistant.setup] Setup failed for remote_homeassistant: No setup function defined.
```

**Comment by azwildfire** [comment]
I am on 0.95.4 and confirm it is working. Try upgrading. 0.94.1 also worked for me.

**Comment by michalterbert** [comment]
Nope. I upgraded to 0.95.4 (Hassio/Docker) and still the same error:
```
2019-07-08 23:33:33 INFO (MainThread) [homeassistant.setup] Setting up remote_homeassistant
2019-07-08 23:33:33 ERROR (MainThread) [homeassistant.setup] Setup failed for remote_homeassistant: No setup function defined.
```

in configuration.yaml I have:
```remote_homeassistant:
     instances:
    - host: publicdomain.eu
      port: 443
      secure: true
      access_token: xxx
      #api_password: !secret http_password
      entity_prefix: "1_"
```

**Comment by lukas-hetzenecker** [comment]
Is `remote_homeassistant` a top-level entry in your configuration.yaml?
Also, your indentation looks wrong - but this could be just a copy and paste error.

Does it look like this?

```
remote_homeassistant:
  instances:
  - host: publicdomain.eu
    port: 443
    secure: true
    access_token: xxx
    entity_prefix: "1_"
```

**Comment by michalterbert** [comment]
@lukas-hetzenecker yes, looks like in your example.

I have one notification:
```
The following components and platforms could not be set up:
- remote_homeassistant
Please check your config.
```
After removed __init__.py file from directory (/config/custom_components/remote_homeassistant)
In logs I can find:
```
2019-07-08 23:50:24 ERROR (MainThread) [homeassistant.setup] Setup failed for remote_homeassistant: Integration not found.
```

**Comment by michalterbert** [comment]
do you have any update?

**Comment by BertilJ** [comment]
I'm on 0.96.5 and I'm getting the same message. 

`Integration not found: remote_homeassistant`

**Comment by jo-me** [comment]
I set it up yesterday and it worked. I just put the `remote_homeassistant.py` file directly in 
`/usr/share/hassio/homeassistant/custom_components`
without any subdirectory.

Maybe also check file permissions against other working custom components

**Comment by jo-me** [comment]
Also, try a entity prefix that does not start with a number. And use only lower-case letters.

**Comment by lukas-hetzenecker** [comment]
Still can't reproduce this issue.
If you're using HACS, you should soon be able to install this plugin via a simple click ( #13 ). This should rule out any problems with the installation.

**Comment by lukas-hetzenecker** [comment]
Please try installing via HACS
