### ISSUE TITLE
Ver 3 small problem

### ISSUE THREAD

**Issue by goldbe4804** [lukas-hetzenecker/home-assistant-remote#81]
1st Thank you for all the work you put into this, it works great for me, i use it to connect 2 remotes ( summer home & my work) to my main instances 
i just updated to ver 3 and now my connection sensor seems not to work the state is "unknown" and does not change.

jeff

**Comment by postlund** [comment]
Do you see anything in the log?

**Comment by goldbe4804** [comment]
the only this i see is


2020-12-09 10:16:18 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
2020-12-09 10:16:18 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook



Logger: aiohttp.websocket
Source: /usr/local/lib/python3.8/site-packages/alexapy/aiohttp/http_websocket.py:599
First occurred: 10:16:18 AM (4 occurrences)
Last logged: 10:16:18 AM

websocket connection is closing.

**Comment by postlund** [comment]
That's an unrelated error, so not helpful here. What version of Home Assistant are you running on the remote host?

**Comment by goldbe4804** [comment]
my 3 units are running  118.5 on rp4 and i get that error from both my remotes

**Comment by goldbe4804** [comment]
btw my setup is yaml

**Comment by postlund** [comment]
Can you test with code in #80?

**Comment by goldbe4804** [comment]
sure ..... but you will need to spell it out a little better than that,  for me .... sorry

**Comment by lukas-hetzenecker** [comment]
Have you installed the integration via HACS?
If yes, you can click on "Reinstall" in the options menu of "Remote Home-Assistant" in HACS (next to "Repository"), and then select "master" and "Install".
You'll then have the most up-to-date code with (hopefully) a working bugfix.

**Comment by goldbe4804** [comment]
Will try and let you knowThank you And be safe !!!On Dec 9, 2020 7:09 PM, Lukas <notifications@github.com> wrote:
Have you installed the integration via HACS?
If yes, you can click on "Reinstall" in the options menu of "Remote Home-Assistant" in HACS (next to "Repository"), and then select "master" and "Install".
You'll then have the most up-to-date code with (hopefully) a working bugfix.

**Comment by lukas-hetzenecker** [comment]
New release published, please reopen this ticket if you still get this error

**Comment by goldbe4804** [comment]
seems to be working fine after the update

thank you !!!!
Jeff Goldberg
Audio Warehouse
170 Gregg St Unit 3
Lodi, NJ 07644
201-368-2632
On 12/13/2020 5:30:31 AM, Lukas <notifications@github.com> wrote:
New release published, please reopen this ticket if you still get this error
