### ISSUE TITLE
lock service not available in master instance

### ISSUE THREAD

**Issue by cjr222** [lukas-hetzenecker/home-assistant-remote#82]
I have this integration up and running great for all my switches, lights, motion sensors, etc but I can't get my zwave locks to work. The entities show up in the master fine but when I try to call the lock.lock service it doesn't exist on the master. I asked in discord about how to manually install the service on the master and they thought the service should pull over from the slave. Any ideas?

**Comment by postlund** [comment]
As stated at the bottom of the readme, you need to manually load components on the client side that are only used on the remote side. So basically add `zwave:` to your config. I intend to add automatic support for this at some point, haven't come around to do so yet though.

**Comment by postlund** [comment]
It was pretty simple to implement, so I went ahead and did it. You can try it out in #83 if you want. If you set up via config flow, just head over to Options and pick `zwave` from the list. Otherwise add it to your YAML config like this:

```yaml
remote_homeassistant:
  instances:
  - host: 10.0.0.2
    load_components:
    - zwave
```

**Comment by cjr222** [comment]
Awesome! Thank you! I missed that special note in the instructions and didn't really understand it until you called it out. All I had to do was add a dummy config entry for lock: and it's now working.

**Comment by postlund** [comment]
The we'll close this!
