### ISSUE TITLE
Regular disconnection since frontend integration

### ISSUE THREAD

**Issue by flouck** [lukas-hetzenecker/home-assistant-remote#84]
Regularly disconect so I have to restart it all to make it connect again. Trying to edit an entity state of the HA slave from the main HA lovelace makes it disconnect. I didn't have this issue before updating to v3.

My logs:

```
Logger: custom_components.remote_homeassistant
Source: custom_components/remote_homeassistant/__init__.py:608
Integration: Remote Home-Assistant
First occurred: 5:21:57 PM (2 occurrences)
Last logged: 5:22:01 PM
could not send data to remote connection: Cannot write to closing transport 
```

**Comment by postlund** [comment]
Should be fixed on `master`.

@lukas-hetzenecker Maybe it's time to make a patch release?

**Comment by flouck** [comment]
What do you mean on master? What shall I do? Sorry for stupid question

**Comment by postlund** [comment]
It's fixed on the `master` branch here in git, but there's no release for it that you can install HACS yet. But I think you can pick to install from `master` if you enable beta releases.

**Comment by lukas-hetzenecker** [comment]
Will publish a release tomorrow morning, sorry for the delay

**Comment by lukas-hetzenecker** [comment]
done, new release published - please test if it is fixed there
and thanks @postlund

**Comment by flouck** [comment]
Seems to be working perfectly now. Thank you to both of you!
