### ISSUE TITLE
Can home-assistant-remote work with Nabu Casa remote access

### ISSUE THREAD

**Issue by john-k-mcdowell** [lukas-hetzenecker/home-assistant-remote#87]
I am running two instances of HA in two different homes.  I have a nabu casa account for each to allow remote access (I had some issues trying to get DuckDNS to work with security turned on, so I stopped forwarding the port and just use the nabu casa generated URL and it works fine to remotely access the UI)

Is it possible to use the nabu casa url as the host for home-assistant-remote setup?  (I have tried in the automatic integration setup but it fails with the error that it can't connect.  The remote URL I am using is of the form:

https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.ui.nabu.casa

**Comment by postlund** [comment]
Don't see any reason why it wouldn't work. Just enter the URL without `https://` into host, use port 443, check both boxes (secure and verify) and enter token. Then you should be good to go.

**Comment by john-k-mcdowell** [comment]
That worked like a champ!! thanks

**Comment by postlund** [comment]
Perfect! Feel free to close the issue!

@lukas-hetzenecker Maybe you can add me as a collaborator so I can close and edit issues?

**Comment by lukas-hetzenecker** [comment]
@postlund you should have gotten an invitation :) 
We should probably move this repo to https://github.com/custom-components then?

**Comment by postlund** [comment]
@lukas-hetzenecker It seems to work 😊👍

I leave that decision up to you, didn't even know that repository existed 😅
