### ISSUE TITLE
Empty value of entity_prefix attribute of connection sensor

### ISSUE THREAD

**Issue by jacekpaszkowski** [lukas-hetzenecker/home-assistant-remote#89]
Hi,

i've noticed that `entity_prefix` attribute is empty. All entities form slave HA have correct prefix. So it's not a serious problem :)

**Comment by postlund** [comment]
Well, yes, that's an unintended feature 😉 I will fix that, it's just a presentation issue so won't affect anything else. Thanks for reporting!

**Comment by postlund** [comment]
Should be fixed by #91.
