### ISSUE TITLE
Restrict what the remote sends

### ISSUE THREAD

**Issue by SylvainGa** [lukas-hetzenecker/home-assistant-remote#94]
Is there a way to restrict what the remote sends to the master? I'm asking because my remote is on DSL. Upload speed is quite limited on DSL and I would prefer not sending data that is not going to be used by the master anyway. 

Thanks.

**Comment by lukas-hetzenecker** [comment]
No, unfortunately there is no way I know of that can limit the amount of data that is pushed by the Websocket API.
This is out of scope of this integration, as home-assistant sends all state changes over the websocket connection. 
(It's actually the other way around as you've described it: The master sends all changes to the remote, the remote then optionally does some filtering.)
